# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/study/verilog/debug/RISCV/mips_cpu/mips_cpu.cache/wt [current_project]
set_property parent.project_path D:/study/verilog/debug/RISCV/mips_cpu/mips_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/study/verilog/debug/RISCV/mips_cpu/mips_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/study/verilog/debug/RISCV/verilog/circuit/ALU.v
  D:/study/verilog/debug/RISCV/verilog/gates/AND_GATE.v
  D:/study/verilog/debug/RISCV/verilog/gates/AND_GATE_10_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/AND_GATE_5_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/AND_GATE_6_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/AND_GATE_7_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/AND_GATE_8_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/AND_GATE_BUS.v
  D:/study/verilog/debug/RISCV/verilog/arithmetic/Adder.v
  D:/study/verilog/debug/RISCV/verilog/wiring/Bit_Extender_12_32_SIGN.v
  D:/study/verilog/debug/RISCV/verilog/wiring/Bit_Extender_20_32.v
  D:/study/verilog/debug/RISCV/verilog/wiring/Bit_Extender_20_32_SIGN.v
  D:/study/verilog/debug/RISCV/verilog/circuit/COMPUTESIGNAL.v
  D:/study/verilog/debug/RISCV/verilog/circuit/CONTROLLER.v
  D:/study/verilog/debug/RISCV/verilog/circuit/CONTROLSIGNAL.v
  D:/study/verilog/debug/RISCV/verilog/arithmetic/Comparator.v
  D:/study/verilog/debug/RISCV/verilog/circuit/DISPLAY.v
  D:/study/verilog/debug/RISCV/verilog/memory/D_Flip_Flop.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Demultiplexer_32.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Demultiplexer_8.v
  D:/study/verilog/debug/RISCV/verilog/circuit/INTRsignalGEN.v
  D:/study/verilog/debug/RISCV/verilog/circuit/IRIECTRL.v
  D:/study/verilog/debug/RISCV/verilog/memory/LogisimCounter.v
  D:/study/verilog/debug/RISCV/verilog/circuit/MAZEMAP.v
  D:/study/verilog/debug/RISCV/verilog/circuit/MIPS_Regifile.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Multiplexer_16.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Multiplexer_bus_16.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Multiplexer_bus_2.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Multiplexer_bus_4.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Multiplexer_bus_8.v
  D:/study/verilog/debug/RISCV/verilog/gates/NOR_GATE_BUS.v
  D:/study/verilog/debug/RISCV/verilog/gates/NOT_GATE.v
  D:/study/verilog/debug/RISCV/verilog/gates/OR_GATE.v
  D:/study/verilog/debug/RISCV/verilog/gates/OR_GATE_11_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/OR_GATE_15_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/OR_GATE_20_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/OR_GATE_8_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/OR_GATE_9_INPUTS.v
  D:/study/verilog/debug/RISCV/verilog/gates/OR_GATE_BUS.v
  D:/study/verilog/debug/RISCV/verilog/plexers/Priority_Encoder.v
  D:/study/verilog/debug/RISCV/verilog/memory/RAM_DATAPLACE.v
  D:/study/verilog/debug/RISCV/verilog/memory/REGISTER_FLIP_FLOP.v
  D:/study/verilog/debug/RISCV/verilog/memory/REGISTER_FLIP_FLOP_PC.v
  D:/study/verilog/debug/RISCV/verilog/circuit/RISCV.v
  D:/study/verilog/debug/RISCV/verilog/memory/ROM_IRPLACE.v
  D:/study/verilog/debug/RISCV/verilog/arithmetic/Shifter_32_bit.v
  D:/study/verilog/debug/RISCV/verilog/arithmetic/Subtractor.v
  D:/study/verilog/debug/RISCV/verilog/gates/XOR_GATE_BUS.v
  D:/study/verilog/debug/RISCV/mips_cpu/mips_cpu.srcs/sources_1/new/myVGA.v
  D:/study/verilog/debug/RISCV/mips_cpu/mips_cpu.srcs/sources_1/new/myTOP.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/study/verilog/debug/RISCV/xdc/LogisimToplevelShell.xdc
set_property used_in_implementation false [get_files D:/study/verilog/debug/RISCV/xdc/LogisimToplevelShell.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top _myPlayer -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef _myPlayer.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file _myPlayer_utilization_synth.rpt -pb _myPlayer_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
